# Generated by Django 6.0.5 on 2026-06-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
