# Generated by Django 6.0.6 on 2026-06-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_resume_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=30),
        ),
    ]
