# Generated by Django 6.0.6 on 2026-06-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_resume_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='local_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='sharepoint_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
