# Generated by Django 6.0.6 on 2026-06-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_resume_local_file_path_resume_sharepoint_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_pdf_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
